{{- if .Values.gateway.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gulley.fullname" . }}-gateway
  labels:
    {{- include "gulley.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
spec:
  type: {{ .Values.gateway.service.type }}
  selector:
    {{- include "gulley.selectorLabels" (dict "root" . "plane" "gateway") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.gateway.service.port }}
      targetPort: http
    - name: metrics
      port: {{ .Values.gateway.metricsPort }}
      targetPort: metrics
{{- end }}
